// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"time"
)

type Article struct {
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"publishedAt"`
}
