---
repository: aereal/nikki/public
coverage:
  if: true
  paths:
    - ../public/coverage/clover.xml
codeToTestRatio:
  code:
    - '../public/src/**/*.{ts,vue}'
    - '!../public/src/**/*.test.ts'
    - '!../public/src/**/*.spec.ts'
  test:
    - '../public/src/**/*.{test,spec}.ts'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report-public
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report-public
comment:
  if: is_pull_request
summary:
  if: is_pull_request
