---

version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  app:
    build: ./app
    command: bundle exec rackup --host 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - "9292:9292"
    environment:
      GOOGLE_OAUTH_CLIENT_ID: $GOOGLE_OAUTH_CLIENT_ID
      GOOGLE_OAUTH_CLIENT_SECRET: $GOOGLE_OAUTH_CLIENT_SECRET
      DB_HOST: db
    depends_on:
      - db
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: yarn run compile:watch
  proxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./proxy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/etc/certs:/etc/certs.d
    depends_on:
      - app
