// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package entrypoint

import (
	"context"
	"github.com/aereal/nikki/backend/env"
	"github.com/aereal/nikki/backend/log"
	"github.com/aereal/nikki/backend/o11y"
	"github.com/aereal/nikki/backend/o11y/service"
	"github.com/aereal/nikki/backend/web"
)

// Injectors from wire.go:

func NewDevEntrypoint(contextContext context.Context) (*Entrypoint, error) {
	output := log.ProvideStdout()
	variables := env.ProvideVariables()
	level, err := env.ProvideLogLevel(variables)
	if err != nil {
		return nil, err
	}
	googleCloudProject := _wireGoogleCloudProjectValue
	version, err := provideDynamicServiceVersion(contextContext)
	if err != nil {
		return nil, err
	}
	logger := log.ProvideLogger(output, level, googleCloudProject, version)
	globalInstrumentationToken := log.ProvideGlobalInstrumentation(logger)
	exporter, err := o11y.ProvideSidecarExporter(contextContext)
	if err != nil {
		return nil, err
	}
	environment := _wireEnvironmentValue
	resource, err := o11y.ProvideResource(contextContext, version, environment)
	if err != nil {
		return nil, err
	}
	tracerProvider := o11y.ProvideTracerProvider(exporter, resource)
	port, err := env.ProvidePort(variables)
	if err != nil {
		return nil, err
	}
	server := web.ProvideServer(tracerProvider, port)
	entrypoint := provideEntrypoint(contextContext, globalInstrumentationToken, server, tracerProvider)
	return entrypoint, nil
}

var (
	_wireGoogleCloudProjectValue = log.GoogleCloudProject("dummy")
	_wireEnvironmentValue        = service.Environment("local")
)
