// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/aereal/nikki/backend/env"
	"github.com/aereal/nikki/backend/infra/db"
	"github.com/aereal/nikki/backend/infra/db/exec"
	"github.com/aereal/nikki/backend/log"
	"github.com/aereal/nikki/backend/o11y"
	"github.com/aereal/nikki/backend/o11y/service"
	"github.com/aereal/nikki/backend/usecases/interactions"
)

// Injectors from wire.go:

func build(contextContext context.Context) (*app, error) {
	output := log.ProvideStdout()
	variables := env.ProvideVariables()
	level, err := env.ProvideLogLevel(variables)
	if err != nil {
		return nil, err
	}
	version := _wireVersionValue
	logger := log.ProvideLogger(output, level, version)
	globalInstrumentationToken := log.ProvideGlobalInstrumentation(logger)
	exporter, err := o11y.ProvideSidecarExporter(contextContext)
	if err != nil {
		return nil, err
	}
	environment := _wireEnvironmentValue
	resource, err := o11y.ProvideResource(contextContext, version, environment)
	if err != nil {
		return nil, err
	}
	tracerProvider := o11y.ProvideTracerProvider(exporter, resource)
	endpoint, err := env.ProvideDBEndpoint(variables)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideDB(tracerProvider, endpoint)
	if err != nil {
		return nil, err
	}
	runner := exec.ProvideRunner(sqlDB)
	articleRepository := db.ProvideArticleRepository(tracerProvider, runner)
	idGenerator := db.ProvideCategoryIDGenerator()
	categoryRepository := db.ProvideCategoryRepository(tracerProvider, runner, idGenerator)
	dbIDGenerator := db.ProvideArticleIDGenerator()
	idGenerator2 := db.ProvideArticleRevisionIDGenerator()
	mtExportFileName, err := env.ProvideMTExportFileName(variables)
	if err != nil {
		return nil, err
	}
	importMTExport := interactions.ProvideImportMTExport(tracerProvider, articleRepository, categoryRepository, dbIDGenerator, idGenerator2, runner, mtExportFileName)
	mainApp := provideApp(globalInstrumentationToken, importMTExport, tracerProvider)
	return mainApp, nil
}

var (
	_wireVersionValue     = service.Version("latest")
	_wireEnvironmentValue = service.Environment("local")
)
