// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"context"
	"github.com/aereal/nikki/backend/infra/db"
	"github.com/aereal/nikki/backend/infra/db/exec"
	"github.com/aereal/nikki/backend/o11y"
)

// Injectors from wire.go:

func NewTestCategoryRepository(contextContext context.Context) (*TestCategoryRepository, error) {
	tracerProvider := o11y.ProvideNoopTracerProvider()
	memoryEndpoint := db.ProvideMemoryEndpoint()
	sqlDB, err := db.ProvideDB(tracerProvider, memoryEndpoint)
	if err != nil {
		return nil, err
	}
	testProvisionedDB, err := provideProvisionedDB(contextContext, sqlDB)
	if err != nil {
		return nil, err
	}
	runner := exec.ProvideRunner(sqlDB)
	categoryRepository := db.ProvideCategoryRepository(tracerProvider, runner)
	testCategoryRepository := provideTestCategoryRepository(testProvisionedDB, categoryRepository)
	return testCategoryRepository, nil
}
