// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aereal/nikki/backend/usecases/ports (interfaces: IDGenerator)
//
// Generated by this command:
//
//	mockgen -typed -package mock -destination ./mock_gen.go github.com/aereal/nikki/backend/usecases/ports IDGenerator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator[ID any] struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder[ID]
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder[ID any] struct {
	mock *MockIDGenerator[ID]
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator[ID any](ctrl *gomock.Controller) *MockIDGenerator[ID] {
	mock := &MockIDGenerator[ID]{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder[ID]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator[ID]) EXPECT() *MockIDGeneratorMockRecorder[ID] {
	return m.recorder
}

// GenerateID mocks base method.
func (m *MockIDGenerator[ID]) GenerateID() ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateID")
	ret0, _ := ret[0].(ID)
	return ret0
}

// GenerateID indicates an expected call of GenerateID.
func (mr *MockIDGeneratorMockRecorder[ID]) GenerateID() *MockIDGeneratorGenerateIDCall[ID] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateID", reflect.TypeOf((*MockIDGenerator[ID])(nil).GenerateID))
	return &MockIDGeneratorGenerateIDCall[ID]{Call: call}
}

// MockIDGeneratorGenerateIDCall wrap *gomock.Call
type MockIDGeneratorGenerateIDCall[ID any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIDGeneratorGenerateIDCall[ID]) Return(arg0 ID) *MockIDGeneratorGenerateIDCall[ID] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIDGeneratorGenerateIDCall[ID]) Do(f func() ID) *MockIDGeneratorGenerateIDCall[ID] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIDGeneratorGenerateIDCall[ID]) DoAndReturn(f func() ID) *MockIDGeneratorGenerateIDCall[ID] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
