// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/aereal/nikki/backend/domain/mock"
	"github.com/aereal/nikki/backend/o11y"
	"github.com/aereal/nikki/backend/usecases/interactions"
	mock2 "github.com/aereal/nikki/backend/usecases/ports/mock"
	mock3 "github.com/aereal/nikki/backend/usecases/unitofwork/mock"
	"go.uber.org/mock/gomock"
)

// Injectors from wire.go:

func NewTestImportMTExport(controller *gomock.Controller, mtExportFileName interactions.MTExportFileName) *TestImportMTExport {
	tracerProvider := o11y.ProvideNoopTracerProvider()
	mockArticleRepository := mock.NewMockArticleRepository(controller)
	mockCategoryRepository := mock.NewMockCategoryRepository(controller)
	mockIDGenerator := mock2.NewArticleIDGenerator(controller)
	mockMockIDGenerator := mock2.NewArticleRevisionIDGenerator(controller)
	runner := mock3.ProvideMockRunner()
	importMTExport := interactions.ProvideImportMTExport(tracerProvider, mockArticleRepository, mockCategoryRepository, mockIDGenerator, mockMockIDGenerator, runner, mtExportFileName)
	testImportMTExport := provideTestImportMTExport(importMTExport, mockArticleRepository, mockCategoryRepository, mockIDGenerator, mockMockIDGenerator)
	return testImportMTExport
}
