source 'https://rubygems.org'

gem 'graphql'
gem 'json-schema'
gem 'jwt'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'pg'
gem 'puma'
gem 'redcarpet'
gem 'sequel'
gem 'sinatra'
gem 'sinatra-contrib', require: nil
gem 'slim'
