// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/aereal/nikki/backend/domain"
)

type Category struct {
	CategoryID domain.CategoryID
	Name       string
}
