// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const importCategories = `-- name: ImportCategories :exec
insert into
  categories (category_id, name)
values
  (?, ?) on conflict (name) do nothing
`

type ImportCategoriesParams struct {
	CategoryID string
	Name       string
}

func (q *Queries) ImportCategories(ctx context.Context, arg ImportCategoriesParams) error {
	_, err := q.db.ExecContext(ctx, importCategories, arg.CategoryID, arg.Name)
	return err
}
