// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aereal/nikki/backend/domain (interfaces: ArticleRepository,CategoryRepository)
//
// Generated by this command:
//
//	mockgen -typed -package mock -destination ./mock_gen.go github.com/aereal/nikki/backend/domain ArticleRepository,CategoryRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/aereal/nikki/backend/domain"
	optional "github.com/aereal/optional"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleRepository is a mock of ArticleRepository interface.
type MockArticleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepositoryMockRecorder
	isgomock struct{}
}

// MockArticleRepositoryMockRecorder is the mock recorder for MockArticleRepository.
type MockArticleRepositoryMockRecorder struct {
	mock *MockArticleRepository
}

// NewMockArticleRepository creates a new mock instance.
func NewMockArticleRepository(ctrl *gomock.Controller) *MockArticleRepository {
	mock := &MockArticleRepository{ctrl: ctrl}
	mock.recorder = &MockArticleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepository) EXPECT() *MockArticleRepositoryMockRecorder {
	return m.recorder
}

// FindArticleBySlug mocks base method.
func (m *MockArticleRepository) FindArticleBySlug(ctx context.Context, slug string) (*domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindArticleBySlug", ctx, slug)
	ret0, _ := ret[0].(*domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindArticleBySlug indicates an expected call of FindArticleBySlug.
func (mr *MockArticleRepositoryMockRecorder) FindArticleBySlug(ctx, slug any) *MockArticleRepositoryFindArticleBySlugCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindArticleBySlug", reflect.TypeOf((*MockArticleRepository)(nil).FindArticleBySlug), ctx, slug)
	return &MockArticleRepositoryFindArticleBySlugCall{Call: call}
}

// MockArticleRepositoryFindArticleBySlugCall wrap *gomock.Call
type MockArticleRepositoryFindArticleBySlugCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArticleRepositoryFindArticleBySlugCall) Return(arg0 *domain.Article, arg1 error) *MockArticleRepositoryFindArticleBySlugCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArticleRepositoryFindArticleBySlugCall) Do(f func(context.Context, string) (*domain.Article, error)) *MockArticleRepositoryFindArticleBySlugCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArticleRepositoryFindArticleBySlugCall) DoAndReturn(f func(context.Context, string) (*domain.Article, error)) *MockArticleRepositoryFindArticleBySlugCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindArticles mocks base method.
func (m *MockArticleRepository) FindArticles(ctx context.Context, first int, direction domain.OrderDirection, cursor optional.Option[time.Time]) ([]*domain.Article, optional.Option[time.Time], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindArticles", ctx, first, direction, cursor)
	ret0, _ := ret[0].([]*domain.Article)
	ret1, _ := ret[1].(optional.Option[time.Time])
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindArticles indicates an expected call of FindArticles.
func (mr *MockArticleRepositoryMockRecorder) FindArticles(ctx, first, direction, cursor any) *MockArticleRepositoryFindArticlesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindArticles", reflect.TypeOf((*MockArticleRepository)(nil).FindArticles), ctx, first, direction, cursor)
	return &MockArticleRepositoryFindArticlesCall{Call: call}
}

// MockArticleRepositoryFindArticlesCall wrap *gomock.Call
type MockArticleRepositoryFindArticlesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArticleRepositoryFindArticlesCall) Return(arg0 []*domain.Article, arg1 optional.Option[time.Time], arg2 error) *MockArticleRepositoryFindArticlesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArticleRepositoryFindArticlesCall) Do(f func(context.Context, int, domain.OrderDirection, optional.Option[time.Time]) ([]*domain.Article, optional.Option[time.Time], error)) *MockArticleRepositoryFindArticlesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArticleRepositoryFindArticlesCall) DoAndReturn(f func(context.Context, int, domain.OrderDirection, optional.Option[time.Time]) ([]*domain.Article, optional.Option[time.Time], error)) *MockArticleRepositoryFindArticlesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ImportArticles mocks base method.
func (m *MockArticleRepository) ImportArticles(ctx context.Context, aggregate *domain.ImportArticlesAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportArticles", ctx, aggregate)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportArticles indicates an expected call of ImportArticles.
func (mr *MockArticleRepositoryMockRecorder) ImportArticles(ctx, aggregate any) *MockArticleRepositoryImportArticlesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportArticles", reflect.TypeOf((*MockArticleRepository)(nil).ImportArticles), ctx, aggregate)
	return &MockArticleRepositoryImportArticlesCall{Call: call}
}

// MockArticleRepositoryImportArticlesCall wrap *gomock.Call
type MockArticleRepositoryImportArticlesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockArticleRepositoryImportArticlesCall) Return(arg0 error) *MockArticleRepositoryImportArticlesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockArticleRepositoryImportArticlesCall) Do(f func(context.Context, *domain.ImportArticlesAggregate) error) *MockArticleRepositoryImportArticlesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockArticleRepositoryImportArticlesCall) DoAndReturn(f func(context.Context, *domain.ImportArticlesAggregate) error) *MockArticleRepositoryImportArticlesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCategoryRepository is a mock of CategoryRepository interface.
type MockCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryMockRecorder is the mock recorder for MockCategoryRepository.
type MockCategoryRepositoryMockRecorder struct {
	mock *MockCategoryRepository
}

// NewMockCategoryRepository creates a new mock instance.
func NewMockCategoryRepository(ctrl *gomock.Controller) *MockCategoryRepository {
	mock := &MockCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepository) EXPECT() *MockCategoryRepositoryMockRecorder {
	return m.recorder
}

// FindCategoriesByNames mocks base method.
func (m *MockCategoryRepository) FindCategoriesByNames(ctx context.Context, names []string) ([]*domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCategoriesByNames", ctx, names)
	ret0, _ := ret[0].([]*domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCategoriesByNames indicates an expected call of FindCategoriesByNames.
func (mr *MockCategoryRepositoryMockRecorder) FindCategoriesByNames(ctx, names any) *MockCategoryRepositoryFindCategoriesByNamesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCategoriesByNames", reflect.TypeOf((*MockCategoryRepository)(nil).FindCategoriesByNames), ctx, names)
	return &MockCategoryRepositoryFindCategoriesByNamesCall{Call: call}
}

// MockCategoryRepositoryFindCategoriesByNamesCall wrap *gomock.Call
type MockCategoryRepositoryFindCategoriesByNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCategoryRepositoryFindCategoriesByNamesCall) Return(arg0 []*domain.Category, arg1 error) *MockCategoryRepositoryFindCategoriesByNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCategoryRepositoryFindCategoriesByNamesCall) Do(f func(context.Context, []string) ([]*domain.Category, error)) *MockCategoryRepositoryFindCategoriesByNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCategoryRepositoryFindCategoriesByNamesCall) DoAndReturn(f func(context.Context, []string) ([]*domain.Category, error)) *MockCategoryRepositoryFindCategoriesByNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ImportCategories mocks base method.
func (m *MockCategoryRepository) ImportCategories(ctx context.Context, names []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCategories", ctx, names)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportCategories indicates an expected call of ImportCategories.
func (mr *MockCategoryRepositoryMockRecorder) ImportCategories(ctx, names any) *MockCategoryRepositoryImportCategoriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCategories", reflect.TypeOf((*MockCategoryRepository)(nil).ImportCategories), ctx, names)
	return &MockCategoryRepositoryImportCategoriesCall{Call: call}
}

// MockCategoryRepositoryImportCategoriesCall wrap *gomock.Call
type MockCategoryRepositoryImportCategoriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCategoryRepositoryImportCategoriesCall) Return(arg0 error) *MockCategoryRepositoryImportCategoriesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCategoryRepositoryImportCategoriesCall) Do(f func(context.Context, []string) error) *MockCategoryRepositoryImportCategoriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCategoryRepositoryImportCategoriesCall) DoAndReturn(f func(context.Context, []string) error) *MockCategoryRepositoryImportCategoriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
