// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/aereal/nikki/backend/domain"
	"github.com/aereal/nikki/backend/infra/db/dto"
)

type Article struct {
	ArticleID domain.ArticleID
	Slug      string
}

type ArticleCategoryMapping struct {
	ArticleID  domain.ArticleID
	CategoryID domain.CategoryID
}

type ArticlePublication struct {
	ArticleID         domain.ArticleID
	ArticleRevisionID domain.ArticleRevisionID
	PublishedAt       dto.DateTime
}

type ArticleRevision struct {
	ArticleRevisionID domain.ArticleRevisionID
	ArticleID         domain.ArticleID
	Title             string
	Body              string
	AuthoredAt        dto.DateTime
}

type Category struct {
	CategoryID domain.CategoryID
	Name       string
}
