// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/aereal/nikki/backend/domain"
	"github.com/aereal/nikki/backend/infra/db/dto"
)

const reviseArticle = `-- name: ReviseArticle :exec
insert into
  article_revisions (
    article_revision_id,
    article_id,
    title,
    body,
    authored_at
  )
values
  (?, ?, ?, ?, ?)
`

type ReviseArticleParams struct {
	ArticleRevisionID domain.ArticleRevisionID
	ArticleID         domain.ArticleID
	Title             string
	Body              string
	AuthoredAt        dto.DateTime
}

func (q *Queries) ReviseArticle(ctx context.Context, arg ReviseArticleParams) error {
	_, err := q.db.ExecContext(ctx, reviseArticle,
		arg.ArticleRevisionID,
		arg.ArticleID,
		arg.Title,
		arg.Body,
		arg.AuthoredAt,
	)
	return err
}
