// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/aereal/nikki/backend/graph"
	"github.com/aereal/nikki/backend/graph/resolvers"
	"github.com/aereal/nikki/backend/o11y"
)

// Injectors from wire.go:

func NewHandler() *Handler {
	tracerProvider := o11y.ProvideNoopTracerProvider()
	resolver := resolvers.ProvideResolver()
	handler := graph.ProviveHandler(tracerProvider, resolver)
	testHandler := provideHandler(handler)
	return testHandler
}
