// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/aereal/nikki/backend/domain/mock"
	"github.com/aereal/nikki/backend/graph"
	"github.com/aereal/nikki/backend/graph/resolvers"
	"github.com/aereal/nikki/backend/o11y"
	"go.uber.org/mock/gomock"
)

// Injectors from wire.go:

func NewHandler(controller *gomock.Controller) *Handler {
	tracerProvider := o11y.ProvideNoopTracerProvider()
	mockArticleRepository := mock.NewMockArticleRepository(controller)
	resolver := resolvers.ProvideResolver(mockArticleRepository)
	handler := graph.ProviveHandler(tracerProvider, resolver)
	testHandler := provideHandler(handler, mockArticleRepository)
	return testHandler
}
